#!/usr/bin/env python3
"""Writes the two generated files of the PXE boot server: dnsmasq.conf (proxy DHCP + TFTP) and boot.ipxe (what a screen boots).

    pxe_config.py --ip 192.168.1.20 --interface eth0 --network 192.168.1.0 --board-url http://192.168.1.20/ --dest /opt/checkin-board-pxe

Proxy DHCP means the router keeps handing out addresses; this server only adds "and boot from here" to the answer, so it
works on a network that already has a DHCP server. Kept apart from install-pxe.sh so the tests can render the files."""
import argparse
import os

DNSMASQ = """\
# Generated by pxe_config.py - proxy DHCP and TFTP for the check-in screens. The router's DHCP is not touched.
port=0
interface={interface}
bind-interfaces
log-dhcp
dhcp-range={network},proxy
enable-tftp
tftp-root={tftp_root}

# iPXE announces itself with option 175: hand it the script. Other PXE clients first get iPXE itself.
dhcp-match=set:ipxe,175
pxe-service=tag:!ipxe,x86PC,"Check-in screen (BIOS)",undionly.kpxe
pxe-service=tag:!ipxe,BC_EFI,"Check-in screen (UEFI)",ipxe.efi
pxe-service=tag:!ipxe,X86-64_EFI,"Check-in screen (UEFI)",ipxe.efi
pxe-service=tag:ipxe,x86PC,"Check-in screen",boot.ipxe
pxe-service=tag:ipxe,BC_EFI,"Check-in screen",boot.ipxe
pxe-service=tag:ipxe,X86-64_EFI,"Check-in screen",boot.ipxe
"""

BOOT_IPXE = """\
#!ipxe
# Generated by pxe_config.py. A screen with a file screens/<its mac with dashes>.ipxe there may set ${{location}}
# (the buildings it shows); everybody else shows the whole board.
set server http://{ip}:{http_port}
set board {board_url}
set location
chain --autofree ${{server}}/screens/${{net0/mac:hexhyp}}.ipxe || echo No file for this screen, showing everybody
kernel ${{server}}/vmlinuz boot=live fetch=${{server}}/filesystem.squashfs ip=dhcp quiet checkin_url=${{board}} checkin_location=${{location}}
initrd ${{server}}/initrd.img
boot
"""


def render(ip, interface, network, board_url, http_port, dest):
    """(dnsmasq.conf text, boot.ipxe text)."""
    for word in (ip, interface, network, board_url):
        if not word or any(c in word for c in " \t\r\n\"'$`\\"):
            raise ValueError("not usable here: %r" % word)
    tftp_root = os.path.join(dest, "tftp")
    return (DNSMASQ.format(interface=interface, network=network, tftp_root=tftp_root),
            BOOT_IPXE.format(ip=ip, http_port=int(http_port), board_url=board_url))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--ip", required=True, help="this server's address on the screens' network")
    ap.add_argument("--interface", required=True)
    ap.add_argument("--network", required=True, help="the network address of that subnet, e.g. 192.168.1.0")
    ap.add_argument("--board-url", required=True, help="where the check-in board is, e.g. http://192.168.1.20/")
    ap.add_argument("--http-port", type=int, default=8069)
    ap.add_argument("--dest", required=True)
    a = ap.parse_args()
    conf, boot = render(a.ip, a.interface, a.network, a.board_url, a.http_port, a.dest)
    os.makedirs(os.path.join(a.dest, "tftp"), exist_ok=True)
    with open(os.path.join(a.dest, "dnsmasq.conf"), "w") as f:
        f.write(conf)
    with open(os.path.join(a.dest, "tftp", "boot.ipxe"), "w") as f:
        f.write(boot)


if __name__ == "__main__":
    main()
