// The clock module in a real browser (run by run.sh against a demo server started with CLOCK=1): the three lines of the box, the time
// zone map that a tap opens, the settings, and the clock's own colour.
const { chromium } = require('playwright');
const URL = 'http://127.0.0.1:' + (process.env.PORT || 8735) + '/';
let failed = 0;
const ok = (cond, what) => { console.log((cond ? 'ok   ' : 'FAIL ') + what); if (!cond) failed++; };
const settle = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 420, height: 1000 } });
  const errors = [];
  page.on('pageerror', e => errors.push(String(e)));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto(URL, { waitUntil: 'networkidle' }); await settle(1500);
  const box = page.locator('.dbox[data-box="clock"] .now');
  ok(await box.count() === 1, 'the clock is an info box like the network and players boxes');
  const time = async () => (await box.locator('b').textContent()).trim();
  ok(/^\d{2}:\d{2}:\d{2}$/.test(await time()), 'the middle line is the time in 24-hour form (' + await time() + ')');
  ok((await box.locator('.nlabel').textContent()).trim() === '' && await box.locator('.row .carousel .t').count() === 0, 'the top and bottom lines are empty to begin with');
  const t1 = await time(); await settle(1500);
  ok(t1 !== await time(), 'the time ticks');
  // settings: 12-hour, .beat and world time
  await page.click('#cog'); await settle(900);
  const sec = page.locator('section[data-box="clock"]');
  await sec.locator('.srow', { hasText: 'Time format' }).locator('button').click(); await settle(300);
  ok(await page.locator('.pop.open .optrow button').count() === 3 && (await page.locator('.pop.open .optrow button').allTextContents()).join() === '12h,12h am/pm,24h' && await page.locator('.pop.open button', { hasText: 'Done' }).count() === 0, 'the time format pop-up is three buttons (12h, 12h am/pm, 24h) and has no Done');
  await page.locator('.pop.open .optrow button', { hasText: '12h am/pm' }).click(); await settle(900);
  ok(await page.locator('.pop.open').count() === 0, 'a tap on one picks it and closes the pop-up');
  await sec.locator('.srow', { hasText: '.beat time' }).locator('input').check(); await settle(900);
  await sec.locator('.srow', { hasText: 'World time' }).locator('input').check(); await settle(900);
  await page.click('#close-settings'); await settle(1800);
  ok(/^\d{1,2}:\d{2}:\d{2} (AM|PM)$/.test(await time()), 'the middle line follows the 12-hour setting (' + await time() + ')');
  ok(/^@\d{3} \.beats$/.test((await box.locator('.nlabel').textContent()).trim()), 'the top line shows the .beat time');
  ok(await box.locator('.row .carousel .t').count() > 0 && /Tokyo/.test(await box.locator('.row .carousel').first().textContent()), 'the bottom line lists world times');
  // the open box: each city with its time on one row, and the map of the real time zone areas
  ok(!(await box.locator('svg.cmap').isVisible()), 'the map is hidden until the box is tapped');
  await box.click({ position: { x: 20, y: 10 } }); await settle(1500);
  const rows = box.locator('.wlist.grid .p');
  ok(await rows.count() === 10, 'the open box lists the ten default cities (' + await rows.count() + ')');
  const sp = await rows.filter({ hasText: 'São Paulo' }).first().evaluate(e => ({ h: e.getBoundingClientRect().height, line: parseFloat(getComputedStyle(e).lineHeight) || 20, t: e.textContent }));
  ok(sp.h < sp.line * 1.6 && /São Paulo\s*\d{1,2}:\d{2}/.test(sp.t), 'a city and its time stay together on one line (' + sp.t + ')');
  ok(!(await box.locator('.row.x-closed').isVisible()), 'the scrolling line gives way to the list while the box is open');
  ok(await box.locator('svg.cmap').isVisible() && await box.locator('svg.cmap .band').count() === 25, 'a tap opens the map with its 25 time zone bands');
  ok(await box.locator('svg.cmap polygon.land').count() >= 10 && await box.locator('svg.cmap .band.here').count() === 1, 'the land is drawn and the band of the clock\'s own time zone is highlighted');
  ok(await box.locator('svg.cmap .city').count() === 10, 'the cities are dots');
  ok(await box.locator('svg.cmap circle.here').count() === 1 && await box.locator('svg.cmap circle.here').evaluate(e => getComputedStyle(e).fill === 'rgb(255, 255, 255)'), 'the clock\'s own place is a white dot');
  const tops = await box.locator('.wlist.grid .p').evaluateAll(els => els.map(e => Math.round(e.getBoundingClientRect().top)));
  ok(tops.length === 10 && tops.filter(t => t === tops[0]).length >= 2, 'the cities are listed two or more on each row (' + tops.join(',') + ')');
  const hrs = box.locator('svg.cmap text.hr');
  ok(await hrs.count() === 50 && (await hrs.nth(25).textContent()) === '0' && (await hrs.nth(27).textContent()) === '+1' && (await hrs.nth(0).textContent()) !== '', 'the hour of each band is along the top and its UTC offset along the bottom');
  ok(await hrs.evaluateAll(els => new Set(els.map(e => getComputedStyle(e).fontSize)).size === 1), 'the UTC markers are the same size as the hours');
  ok(await box.locator('.cmapnote').count() === 0, 'there is no explaining text under the map');
  ok(await box.locator('svg.cmap .city').first().getAttribute('r') === '3.4', 'the city dots are bigger');
  const w = await box.evaluate(e => ({ svg: e.querySelector('svg.cmap').getBoundingClientRect().width, row: e.querySelector('.worldmap').parentNode.getBoundingClientRect().width }));
  ok(w.svg > w.row * 0.95, 'the map is as wide as its row (' + Math.round(w.svg) + ' of ' + Math.round(w.row) + ')');
  // removing and adding a city, and the clock's own time zone
  await page.click('#cog'); await settle(900);
  ok(await sec.locator('.wpicker .tag:visible').count() === 0 && (await sec.locator('.wpicker > div:first-child > .srow button').first().textContent()) === 'Edit', 'the cities are one row with an Edit button, the list is not in the settings');
  ok(await sec.locator('.srow.edit').first().evaluate(e => getComputedStyle(e).alignItems === 'flex-start'), 'an Edit button sits at the top right of its row');
  await sec.locator('.wpicker .srow', { hasText: 'Cities' }).locator('button.pill-s').first().click(); await settle(300);
  await page.locator('.pop.open .tag', { hasText: 'Moscow' }).locator('button').click(); await settle(900);
  ok(await page.locator('.pop.open .tag', { hasText: 'Moscow' }).count() === 0 && await page.locator('.pop.open .tag').count() === 9, 'a city is removed from the list in the Edit pop-up');
  await page.locator('.pop.open .srow', { hasText: 'Cities' }).locator('button.pill-s').first().click(); await settle(300);
  const opts = await page.locator('.pop.open .choice').allTextContents();
  ok(opts.some(t => /^Stockholm/.test(t)) && !opts.some(t => /^Tokyo/.test(t)), 'the Add pop-up offers the cities that are not in the list yet (' + opts.length + ')');
  await page.locator('.pop.open input').fill('stock'); await settle(300);
  ok(await page.locator('.pop.open .choice').count() === 1, 'typing filters the list');
  await page.locator('.pop.open .choice', { hasText: 'Stockholm' }).click(); await settle(900);
  ok(await page.locator('.pop.open .tag', { hasText: 'Stockholm' }).count() === 1, 'a city is added');
  await page.locator('.pop.open button', { hasText: 'Done' }).click(); await settle(300);
  ok(await sec.locator('.srow', { hasText: /^Time zone/ }).count() === 0, 'the time zone is not a clock setting any more');
  const about = page.locator('section[data-box="about"]');
  await about.locator('.srow', { hasText: 'Time zone' }).locator('button').click(); await settle(300);
  const tk = (await page.locator('.pop.open select').last().locator('option').allTextContents()).filter(t => /^Tokyo/.test(t))[0];
  await page.locator('.pop.open select').last().selectOption({ label: tk }); await settle(900);
  await page.locator('.pop.open button', { hasText: 'Done' }).click(); await settle(300);
  ok(/Tokyo/.test(await about.locator('.srow', { hasText: 'Time zone' }).first().textContent()), 'the common time zone (in About) is set from the city list');
  const tzRow = about.locator('.srow', { hasText: 'Time zone' }).first();
  const place = await tzRow.evaluate(r => { const b = r.querySelector('button').getBoundingClientRect(), q = r.getBoundingClientRect(), t = r.querySelector('.sub').getBoundingClientRect(); return { top: b.top - q.top, right: q.right - b.right, lines: Math.round(t.height / 16) }; });
  ok(place.top < 14 && place.right < 2 && place.lines >= 2, 'with a long text under it the Edit button stays at the top right of the row, the text wraps (' + Math.round(place.top) + 'px from the top, ' + place.lines + ' lines)');
  await page.click('#close-settings'); await settle(1800);
  const tokyo = await page.evaluate(() => S.clock.cities.filter(c => c.title === 'Tokyo').length);
  const shown = (await time()).replace(/:\d{2} (AM|PM)$/, ' $1');
  const tokyoNow = await page.evaluate(() => new Date().toLocaleTimeString('en-US', { timeZone: 'Asia/Tokyo', hour: 'numeric', minute: '2-digit' }));
  ok(shown === tokyoNow, 'the clock shows Tokyo time (' + shown + ' / ' + tokyoNow + ')');
  ok(tokyo === 1 && await box.locator('.wlist.grid .p', { hasText: 'Stockholm' }).count() === 1, 'the list follows the settings');
  // the colour
  await page.click('#cog'); await settle(900);
  await page.locator('[data-box="appearance"] .srow', { hasText: 'Clock colour' }).locator('button').first().click(); await settle(300);
  await page.locator('.pop.open .swatch[aria-label="Bright pink"]').click(); await settle(900);
  await page.click('#close-settings'); await settle(500);
  ok(await page.locator('.dbox[data-box="clock"].c-bright-pink').count() === 1, 'the clock takes the colour picked in Settings');
  // Selected network and Global main are colours too
  const clockPick = async name => { await page.click('#cog'); await settle(800);
    await page.locator('[data-box="appearance"] .srow', { hasText: 'Clock colour' }).locator('button').first().click(); await settle(300);
    await page.locator('.pop.open .swatch[aria-label="' + name + '"]').click(); await settle(900); await page.click('#close-settings'); await settle(500); };
  await page.click('#cog'); await settle(800);
  await page.locator('[data-box="appearance"] .srow', { hasText: 'Clock colour' }).locator('button').first().click(); await settle(300);
  const ids = await page.locator('.pop.open .swatch').evaluateAll(els => els.map(e => e.getAttribute('data-id')));
  ok(ids.length === 15 && ids[0] === 'global' && ids[8] === 'white' && !ids.includes('network') && !ids.includes('bright-orange'), 'the palette starts with Global main and has no "Selected network" (' + ids.join(' ') + ')');
  await page.keyboard.press('Escape'); await page.click('#close-settings'); await settle(400);
  const clockBox = page.locator('.dbox[data-box="clock"]');
  await clockPick('Global main');
  ok(await clockBox.evaluate(e => e.classList.contains('c-global')), 'Global main: the clock takes it');
  await page.click('#cog'); await settle(800);
  await page.locator('[data-box="colours"] .srow', { hasText: 'Global main colour' }).locator('input[type=color]').fill('#00aa55'); await settle(900);
  ok(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--c-global').trim()) === '#00aa55', 'the Global main picker changes the colour everywhere it is used at once');
  ok(await page.evaluate(() => { const c = document.querySelector('#set-boxes .cbox.neutral:checked'); return !!c && getComputedStyle(c).backgroundColor === 'rgb(0, 170, 85)'; }), 'and so do the grey tick boxes (they use Global main)');
  await page.click('#close-settings'); await settle(400);
  ok(await clockBox.locator('.now').evaluate(e => getComputedStyle(e).borderTopColor) === 'rgb(' + [0x00 + Math.round((255 - 0) * 0.45), 0xaa + Math.round((255 - 0xaa) * 0.45), 0x55 + Math.round((255 - 0x55) * 0.45)].join(', ') + ')', 'and the border of the box is its lighter shade');
  // world time off: the map and the list go, the box stays
  await page.click('#cog'); await settle(900);
  await sec.locator('.srow', { hasText: 'World time' }).locator('input').uncheck(); await settle(900);
  await page.click('#close-settings'); await settle(1800);
  ok(await box.locator('.row .carousel .t').count() === 0 && !(await box.locator('svg.cmap').isVisible()), 'with world time off the list and the map are gone');
  // the large clock: the time takes the rows that .beat and world time leave free, and the box never changes height
  const geo = async () => box.evaluate(e => { const b = e.querySelector(':scope > b'); return { h: Math.round(e.getBoundingClientRect().height), fs: parseFloat(getComputedStyle(b).fontSize), mode: e.getAttribute('data-title-rows'), open: e.classList.contains('open') }; });
  const h0 = (await geo()).h, fs0 = (await geo()).fs;
  await page.click('#cog'); await settle(900);
  await sec.locator('.srow', { hasText: 'Large clock' }).locator('input').check(); await settle(900);
  await page.click('#close-settings'); await settle(1800);
  let g = await geo();
  ok(g.mode === 'lower' && g.fs > fs0 * 1.3 && g.h === h0, '.beat on, world off: the time fills the two lower rows (' + g.fs + 'px, box ' + g.h + 'px)');
  await box.click({ position: { x: 20, y: 10 } }); await settle(500);
  g = await geo();
  ok(!g.open && g.h === h0 && await box.evaluate(e => !e.hasAttribute('role')), 'with nothing to show a tap does not open (and so does not shrink) the box');
  await page.click('#cog'); await settle(900);
  await sec.locator('.srow', { hasText: '.beat time' }).locator('input').uncheck(); await settle(900);
  await page.click('#close-settings'); await settle(1800);
  const full = await geo();
  ok(full.mode === 'full' && full.fs > g.fs * 0.97 && full.h === h0, 'both off: the time fills all three rows (' + full.fs + 'px)');
  const tw = await box.evaluate(e => { const b = e.querySelector(':scope > b'), r = document.createRange(); r.selectNodeContents(b); return [r.getBoundingClientRect().width, e.clientWidth]; });
  ok(tw[0] <= tw[1], 'and the text fits the box (' + Math.round(tw[0]) + ' of ' + tw[1] + ')');
  await page.click('#cog'); await settle(900);
  await sec.locator('.srow', { hasText: 'World time' }).locator('input').check(); await settle(900);
  await page.click('#close-settings'); await settle(1800);
  g = await geo();
  ok(g.mode === 'upper' && g.h === h0, 'world on, .beat off: the time fills the top and middle rows');
  await page.click('#cog'); await settle(900);
  await sec.locator('.srow', { hasText: '.beat time' }).locator('input').check(); await settle(900);
  await page.click('#close-settings'); await settle(1800);
  g = await geo();
  ok(g.mode === null && Math.abs(g.fs - fs0) < 1, 'both on: the time is back in the middle row, the size of the other middle rows');
  await page.click('#cog'); await settle(900);
  await sec.locator('.srow', { hasText: 'World time' }).locator('input').uncheck(); await settle(900);
  await page.click('#close-settings'); await settle(1800);
  ok(errors.length === 0, 'no JavaScript or console errors' + (errors.length ? ': ' + errors.join(' | ') : ''));
  await browser.close();
  console.log(failed ? failed + ' check(s) failed' : 'all checks passed');
  process.exit(failed ? 1 : 0);
})();
