// The openMenu link box (run by run.sh against a demo server started with OPENMENU=1 FAKEPLAYERS=1): the Dreamcast's status, the players who
// can be joined, the card's games with a search box, and Start / Join asking first and queueing the launch.
const { chromium } = require('playwright');
const URL = 'http://127.0.0.1:' + (process.env.PORT || 8740) + '/';
let failed = 0;
const ok = (cond, what) => { console.log((cond ? 'ok   ' : 'FAIL ') + what); if (!cond) failed++; };
const settle = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 420, height: 1400 } });
  const errors = [];
  const questions = [];
  page.on('pageerror', e => errors.push(String(e)));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text().slice(0, 150)); });
  page.on('dialog', d => { questions.push(d.message()); d.accept(); });
  await page.goto(URL, { waitUntil: 'networkidle' }); await settle(5500);
  const box = page.locator('.dbox[data-box="openmenu"] .now');
  ok(await box.count() === 1, 'the openMenu link has a box on the main page');
  ok((await box.locator('.nlabel').textContent()).includes('Dreamcast (openMenu)'), 'with its own top line');
  ok((await box.locator('b').first().textContent()).trim() === 'Connected', 'the title says the Dreamcast is connected');
  ok(/72 games on the card/.test(await box.textContent()), 'and the note counts the games');
  await box.click({ position: { x: 20, y: 10 } }); await settle(700);
  ok(await box.evaluate(e => e.classList.contains('open')), 'tapping opens the box');
  const games = box.locator('.wlist').nth(1), join = box.locator('.wlist').nth(0);
  ok(await games.locator('.p').count() === 60, 'the games list stops at 60 rows (' + await games.locator('.p').count() + ')');
  ok(/12 more: use the search/.test(await box.textContent()), 'with a hint to search');
  await box.locator('input[aria-label="Search the card"]').fill('crazy'); await settle(300);
  ok(await games.locator('.p').count() === 1 && /Crazy Taxi/.test(await games.textContent()), 'the search narrows the list');
  ok(await join.locator('.p', { hasText: 'Dave' }).locator('button', { hasText: 'Join' }).count() === 1, 'a player in a game that is on the card has a Join button');
  ok(await join.locator('.p', { hasText: 'Eve' }).count() === 0, 'and one in a game that is not on the card is not listed');
  await page.evaluate(() => { S.openmenu = Object.assign({}, S.openmenu, { connected: false }); engineUpdate(); });
  ok(await games.locator('button').first().isDisabled(), 'while the Dreamcast is not connected the buttons are off');
  await page.evaluate(() => { S.openmenu = Object.assign({}, S.openmenu, { connected: true }); engineUpdate(); });
  await settle(300);
  ok(await games.locator('button').first().isEnabled(), 'and on again when it is');
  await games.locator('.p', { hasText: 'Crazy Taxi' }).locator('button', { hasText: 'Start' }).click(); await settle(2500);
  ok(questions.length === 1 && /Start Crazy Taxi on the Dreamcast\?/.test(questions[0]), 'Start asks first, naming the game (' + questions.join('|') + ')');
  ok(/Waiting for the Dreamcast to start Crazy Taxi|Starting Crazy Taxi|Sent\./.test(await box.textContent()), 'and the box says the game is on its way');
  ok(errors.length === 0, 'no JavaScript or console errors' + (errors.length ? ': ' + errors.join(' | ') : ''));
  await browser.close();
  console.log(failed ? failed + ' check(s) failed' : 'all checks passed');
  process.exit(failed ? 1 : 0);
})();
